# **Launch Sites Locations Analysis with Folium**

The launch success rate may depend on the location and attributes of the launch site, i.e., the initial position of rocket trajectories.  
This notebook uses interactive visual map analytics to discover factors about launch location that may contribute to successful outcomes.

**Contents:**  
- Mark all launch sites on a map.
- Mark all launch outcomes (successful/failed launches) for each launch site on the map.
- Calculate and mark the distance between a launch site to its surrounding infrastructure including:
    - Distance to Closest Coastline
    - Distance to Closest City
    - Distance to Closest Railway

#### Import Libraries

In [1]:
#!pip3 install folium
#!pip3 install wget

In [1]:
import folium
import wget
import pandas as pd
import numpy as np

In [2]:
# Import folium MarkerCluster plugin
from folium.plugins import MarkerCluster
# Import folium MousePosition plugin
from folium.plugins import MousePosition
# Import folium DivIcon plugin
from folium.features import DivIcon

### Mark all launch sites on a map

Add each site's location on a map using latitude and longitude coordinates

In [3]:
# Download and read the `spacex_launch_geo.csv`, dataset augmented with coordinates for launch sites.
spacex_csv_file = wget.download('https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/datasets/spacex_launch_geo.csv')
spacex_df=pd.read_csv(spacex_csv_file)

In [4]:
spacex_df.shape

(56, 13)

Show coordinates for each site:

In [5]:
# Select relevant sub-columns: `Launch Site`, `Lat(Latitude)`, `Long(Longitude)`, `class`
spacex_df = spacex_df[['Launch Site', 'Lat', 'Long', 'class']]
launch_sites_df = spacex_df.groupby(['Launch Site'], as_index=False).first()
launch_sites_df = launch_sites_df[['Launch Site', 'Lat', 'Long']]
launch_sites_df

    Launch Site        Lat        Long
0   CCAFS LC-40  28.562302  -80.577356
1  CCAFS SLC-40  28.563197  -80.576820
2    KSC LC-39A  28.573255  -80.646895
3   VAFB SLC-4E  34.632834 -120.610745

With these coordinates, we can visualize launch locations on a map.

**<span style="color:MediumBlue;">(1). Initialize map with default location at NASA space center.**

We first need to create a folium `Map` object, with an initial center location to be NASA Johnson Space Center at Houston, Texas.

In [6]:
# Start location is NASA Johnson Space Center
nasa_coordinate = [29.559684888503615, -95.0830971930759]
site_map = folium.Map(location=nasa_coordinate, zoom_start=10)

In [7]:
site_map

Use `folium.Circle` to add a highlighted circle area with a text label for NASA Johnson Space Center.

In [8]:
# Create a blue circle at NASA Johnson Space Center's coordinate with a popup label showing its name
circle = folium.Circle(nasa_coordinate, radius=1000, color='#d35400', fill=True).add_child(folium.Popup('NASA Johnson Space Center'))
# Create a blue circle at NASA Johnson Space Center's coordinate with a icon showing its name
marker = folium.map.Marker(
    nasa_coordinate,
    # Create an icon as a text label
    icon=DivIcon(
        icon_size=(20,20),
        icon_anchor=(0,0),
        html='<div style="font-size: 12; color:#d35400;"><b>%s</b></div>' % 'NASA JSC',
        )
    )
site_map.add_child(circle)
site_map.add_child(marker)

Map now shows a small yellow circle near the city of Houston.  
--- <span style="color:crimson;">***We can zoom in and out with cursor/mouse.***

**<span style="color:MediumBlue;">(2). Map all launch sites.**

Now I will create and add `folium.Circle` and `folium.Marker` for each launch site on the site map.

In [9]:
## get coordinates of all four launch sites:
tab = spacex_df.groupby('Launch Site').max()
coords = [] #empty list
for index, row in tab.iterrows(): 
    mylist = [row.Lat, row.Long]
    coords.append(mylist)   
#

In [10]:
# Initial the map
site_map = folium.Map(location=nasa_coordinate, zoom_start=5)

# For each launch site, add a Circle object based on its coordinate (Lat, Long) values. In addition, add Launch site name as a popup label

## ----------- CCAFS LC-40
circle = folium.Circle(coords[0], radius=1000, color='#d35400', fill=True).add_child(folium.Popup('CCAFS LC-40'))
marker = folium.map.Marker(
    coords[0],
    # Create an icon as a text label
    icon=DivIcon(
        icon_size=(20,20),
        icon_anchor=(0,0),
        html='<div style="font-size: 12; color:#d35400;"><b>%s</b></div>' % 'CCAFS LC-40',
        )
    )

site_map.add_child(circle)
site_map.add_child(marker)


## ----------- CCAFS SLC-40
circle = folium.Circle(coords[1], radius=1000, color='#d35400', fill=True).add_child(folium.Popup('CCAFS SLC-40'))
marker = folium.map.Marker(
    coords[1],
    # Create an icon as a text label
    icon=DivIcon(
        icon_size=(20,20),
        icon_anchor=(0,0),
        html='<div style="font-size: 12; color:#d35400;"><b>%s</b></div>' % 'CCAFS SLC-40',
        )
    )

site_map.add_child(circle)
site_map.add_child(marker)


## ------------ KSC LC-39A
circle = folium.Circle(coords[2], radius=1000, color='#d35400', fill=True).add_child(folium.Popup('KSC LC-39A'))
marker = folium.map.Marker(
    coords[2],
    # Create an icon as a text label
    icon=DivIcon(
        icon_size=(20,20),
        icon_anchor=(0,0),
        html='<div style="font-size: 12; color:#d35400;"><b>%s</b></div>' % 'KSC LC-39A',
        )
    )

site_map.add_child(circle)
site_map.add_child(marker)


## ------------ VAFB SLC-4E
circle = folium.Circle(coords[3], radius=1000, color='#d35400', fill=True).add_child(folium.Popup('VAFB SLC-4E'))
marker = folium.map.Marker(
    coords[3],
    # Create an icon as a text label
    icon=DivIcon(
        icon_size=(20,20),
        icon_anchor=(0,0),
        html='<div style="font-size: 12; color:#d35400;"><b>%s</b></div>' % 'VAFB SLC-4E',
        )
    )

site_map.add_child(circle)
site_map.add_child(marker)

#

Now we have four markers for all four launch sites: three in Florida and one in California.  
<span style="color:crimson;">**We can explore the map by zoom-in/out the marked areas.**

**Observations:**  

✔️ Launch sites are located in either Florida or southern California.  
✔️ All launch sites are close to the coast: minimizing the risk of having any debris dropping or exploding near residential areas.  
✔️ All launch sites are relatively close to the equator: easier to launch into the equatorial orbit.

### Mark the success/failed launches for each site on the map

Now add the launch outcomes for each site, so we can see how success rate differs by launch site.

In [11]:
spacex_df.tail(10)

     Launch Site        Lat       Long  class
46    KSC LC-39A  28.573255 -80.646895      1
47    KSC LC-39A  28.573255 -80.646895      1
48    KSC LC-39A  28.573255 -80.646895      1
49  CCAFS SLC-40  28.563197 -80.576820      1
50  CCAFS SLC-40  28.563197 -80.576820      1
51  CCAFS SLC-40  28.563197 -80.576820      0
52  CCAFS SLC-40  28.563197 -80.576820      0
53  CCAFS SLC-40  28.563197 -80.576820      0
54  CCAFS SLC-40  28.563197 -80.576820      1
55  CCAFS SLC-40  28.563197 -80.576820      0

Next create markers for all launch records:  
* Green marker if a launch was successful `(class=1)`,  
* Red marker if a launch failed `(class=0)`

Since each site has multiple launches, use marker clusters to simplify a map while many markers have the same coordinate.

First create a `MarkerCluster` object

In [12]:
marker_cluster = MarkerCluster()

Create a new column in `launch_sites` dataframe called `marker_color` to store the marker colors based on the `class` value

In [14]:
# Apply a function to check the value of `class` column
# If class=1, marker_color value will be green
# If class=0, marker_color value will be red

In [13]:
# Function to assign color to launch outcome
def assign_marker_color(launch_outcome):
    if launch_outcome == 1:
        return 'green'
    else:
        return 'red'
    
spacex_df['marker_color'] = spacex_df['class'].apply(assign_marker_color)
spacex_df.tail(10)

     Launch Site        Lat       Long  class marker_color
46    KSC LC-39A  28.573255 -80.646895      1        green
47    KSC LC-39A  28.573255 -80.646895      1        green
48    KSC LC-39A  28.573255 -80.646895      1        green
49  CCAFS SLC-40  28.563197 -80.576820      1        green
50  CCAFS SLC-40  28.563197 -80.576820      1        green
51  CCAFS SLC-40  28.563197 -80.576820      0          red
52  CCAFS SLC-40  28.563197 -80.576820      0          red
53  CCAFS SLC-40  28.563197 -80.576820      0          red
54  CCAFS SLC-40  28.563197 -80.576820      1        green
55  CCAFS SLC-40  28.563197 -80.576820      0          red

In [16]:
## alternative method: 
#spacex_df.drop(columns='marker_color')
#spacex_df['marker_color'] = np.where(spacex_df['class'] == 1, 'green', 'red')
#spacex_df.tail()

For each launch, add a `folium.Marker` to `marker_cluster`:

In [15]:
# Add marker_cluster to current site_map
site_map.add_child(marker_cluster)

# for each row in spacex_df data frame
# create a Marker object with its coordinate
# and customize the Marker's icon property to indicate if this launch was successed or failed, 
# e.g., icon=folium.Icon(color='white', icon_color=row['marker_color']
for index, record in spacex_df.iterrows():
    # TODO: Create and add a Marker cluster to the site map
    marker = folium.Marker(([record.Lat, record.Long]), icon=folium.Icon(color='white', icon_color=record['marker_color']))
    marker_cluster.add_child(marker)

site_map.save("map_marker.html")
site_map
#

<span style="color:crimson;">**Can zoom in to see success/failure markers.**

<center>
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_3/images/launch_site_marker_cluster.png">
</center>

<center>
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_3/images/launch_site_marker_cluster_zoomed.png">
</center>

**Observations:**  
✔️ Site KSC LC-39A has the best overall performance.   
✔️ The other three sites have more failures than successes.

### Calculate the distances between a launch site to its proximities

Next I explore the distance to nearest infrastrue and coastline for each launch site.

First add a `MousePosition` on the map to get coordinates for any point when hovering a mouse over a location on the map.

In [16]:
# Add Mouse Position to get the coordinate (Lat, Long) for a mouse over on the map
formatter = "function(num) {return L.Util.formatNum(num, 5);};"
mouse_position = MousePosition(
    position='topright',
    separator=' Long: ',
    empty_string='NaN',
    lng_first=False,
    num_digits=20,
    prefix='Lat:',
    lat_formatter=formatter,
    lng_formatter=formatter,
)

site_map.add_child(mouse_position)
site_map

***Define function to calculate the distance between two points on the map based on their `Lat` and `Long` values:***

In [17]:
from math import sin, cos, sqrt, atan2, radians

def calculate_distance(lat1, lon1, lat2, lon2):
    # approximate radius of earth in km
    R = 6373.0

    lat1 = radians(lat1)
    lon1 = radians(lon1)
    lat2 = radians(lat2)
    lon2 = radians(lon2)

    dlon = lon2 - lon1
    dlat = lat2 - lat1

    a = sin(dlat / 2)**2 + cos(lat1) * cos(lat2) * sin(dlon / 2)**2
    c = 2 * atan2(sqrt(a), sqrt(1 - a))

    distance = R * c
    return distance

#### <span style="color:blue;">**Distance to Closest Coastline**

* Mark down a point on the closest coastline using MousePosition.
* Then calculate the distance between the coastline point and the launch site.

In [18]:
# sw. Choose launch site (2) KSC LC-39A
# MousePosition CLOSEST COASTLINE:
coord_coast = [28.60997, -80.59635]
distance_coastline = calculate_distance(launch_sites_df.loc[2, 'Lat'], launch_sites_df.loc[2, 'Long'], coord_coast[0], coord_coast[1])
distance_coastline
#

6.406814609392769

Now create a `folium.Marker` to show the distance

In [19]:
# Create and add a folium.Marker on your selected closest coastline point on the map
# Display the distance between coastline point and launch site using the icon property 
# for example
# distance_marker = folium.Marker(
#    coordinate,
#    icon=DivIcon(
#        icon_size=(20,20),
#        icon_anchor=(0,0),
#        html='<div style="font-size: 12; color:#d35400;"><b>%s</b></div>' % "{:10.2f} KM".format(distance),
#        )
#    )


coord_coast = [28.60997, -80.59635]

distance_marker = folium.Marker(
    coord_coast,
    icon=DivIcon(
        icon_size=(20,20),
        icon_anchor=(0,0),
        html='<div style="font-size: 12; color:#d35400;"><b>%s</b></div>' % "{:10.2f} KM".format(distance_coastline),
        )
    )

site_map.add_child(distance_marker)
site_map

#

Next draw a `PolyLine` between a launch site to the selected coastline point

In [20]:
# Create a `folium.PolyLine` object using the coastline coordinates and launch site coordinate
# lines=folium.PolyLine(locations=coordinates, weight=1)

points = []
coord_coast = [28.60997, -80.59635]
points.append(coord_coast)
points.append([launch_sites_df.loc[2, 'Lat'], launch_sites_df.loc[2, 'Long']])

lines=folium.PolyLine(locations=points, weight=1)
site_map.add_child(lines)
site_map.save("map_coast.html")


#

In [21]:
## sx
points = []
coord_coast = [28.57495, -80.57157]

points.append(coord_coast)
points.append([launch_sites_df.loc[2, 'Lat'], launch_sites_df.loc[2, 'Long']])
points

[[28.57495, -80.57157], [np.float64(28.57325457), np.float64(-80.64689529)]]

<center>
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_3/images/launch_site_marker_distance.png">
</center>

#### <span style="color:blue;">**Distance to Closest City**

* Mark down a point on the closest city using MousePosition.
* Then calculate the distance between the city and the launch site.

Next explore closest city, railway, highway, etc.

A railway map symbol may look like this:

<center>
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_3/images/railway.png">
</center>

A highway map symbol may look like this:

<center>
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_3/images/highway.png">
</center>

A city map symbol may look like this:

<center>
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_3/images/city.png">
</center>

In [22]:
# Create a marker with distance to a closest city, railway, highway, etc.
# Draw a line between the marker to the launch site

# sw. Choose launch site (2) KSC LC-39A
# MousePosition for CLOSEST CITY:   
coord_city = [28.612, -80.808]
distance_city = calculate_distance(launch_sites_df.loc[2, 'Lat'], launch_sites_df.loc[2, 'Long'], coord_city[0], coord_city[1])
distance_city
#

16.313787812282676

In [23]:
distance_marker = folium.Marker(
    coord_city,
    icon=DivIcon(
        icon_size=(20,20),
        icon_anchor=(0,0),
        html='<div style="font-size: 12; color:#d35400;"><b>%s</b></div>' % "{:10.2f} KM".format(distance_city),
        )
    )

site_map.add_child(distance_marker)
site_map
#

In [24]:
points = []
points.append(coord_city)
points.append([launch_sites_df.loc[2, 'Lat'], launch_sites_df.loc[2, 'Long']])

lines=folium.PolyLine(locations=points, color='red', weight=1)
site_map.add_child(lines)
site_map.save("map_city.html")

#

#### <span style="color:blue;">**Distance to Closest Railway**

* Mark down a point on the closest railway using MousePosition.
* Then calculate the distance between the railway point and the launch site.

In [26]:

# sw. Choose launch site (2) KSC LC-39A
# CLOEST RAILWAY 

# MousePosition 

coord_rail = [28.57322, -80.5852]
distance_rail = calculate_distance(launch_sites_df.loc[2, 'Lat'], launch_sites_df.loc[2, 'Long'], coord_rail[0], coord_rail[1])

distance_marker = folium.Marker(
    coord_rail,
    icon=DivIcon(
        icon_size=(20,20),
        icon_anchor=(0,0),
        html='<div style="font-size: 12; color:#d35400;"><b>%s</b></div>' % "{:10.2f} KM".format(distance_rail),
        )
    )

points = []
points.append(coord_rail)
points.append([launch_sites_df.loc[2, 'Lat'], launch_sites_df.loc[2, 'Long']])

lines=folium.PolyLine(locations=points, color = 'green', weight=1)

site_map.add_child(distance_marker)
site_map.add_child(lines)

site_map.save("map_railway.html")
site_map

In [ ]:
launch_sites_df

    Launch Site        Lat        Long
0   CCAFS LC-40  28.562302  -80.577356
1  CCAFS SLC-40  28.563197  -80.576820
2    KSC LC-39A  28.573255  -80.646895
3   VAFB SLC-4E  34.632834 -120.610745

**For site KSC LC-39A:**  
Distance to nearest railway: 6.03km;  coastline: 6.41km;  city: 16.31km

**Observations:**  

✔️ Launch sites are close to coastline to reduce the risk of debris dropping near residential areas.  
✔️ Launch sites are close to railways and highways to ensure supply of resources.  
✔️ Launch sites are far from cities to minimize risk of failed launches causing danger to populated areas.